title: УНФФ
email: sevan@1cmagnitka.ru
baseurl: "/franchisee-manag-doc.github.io"

theme: just-the-docs
plugins:
  - jekyll-feed

search_enabled: false

include:
  - _pages

collections:
  pages:
    output: true
    permalink: /:path/

just_the_docs:
  aux_links:
  - title: "Custom CSS"
    url: "assets/css/custom.css"

defaults:
  - scope:
      path: ""
      type: "assets"
    values:
      assets:
        css: "assets/css/custom.css"

callouts:
  feedback:
    color: blue