title: УНФФ
email: sevan@1cmagnitka.ru
baseurl: "/franchisee-manag-doc.github.io"

theme: just-the-docs
plugins:
  - jekyll-feed

search_enabled: false

include:
  - _pages

collections:
  pages:
    output: true
    permalink: /:path/